# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170625_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
