# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20170625_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ClientProfile'),
        ),
    ]
