# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20170625_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.ClientProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='youngs_registered',
            field=models.ManyToManyField(blank=True, null=True, to='users.YoungProfile'),
        ),
    ]
