# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170625_1447'),
        ('jobs', '0005_auto_20170625_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='youngs_requests',
            field=models.ManyToManyField(blank=True, null=True, related_name='services_requestions', to='users.YoungProfile'),
        ),
        migrations.AlterField(
            model_name='services',
            name='interest_area',
            field=models.CharField(choices=[(b'Aricultura', b'AGR'), (b'Ganaderia', b'GAN'), (b'Mineria', b'MIN'), (b'Ingenieria', b'ING'), (b'Sistemas', b'SIS'), (b'Mecatronica', b'MEC'), (b'Licenciatura', b'LIC')], max_length=255),
        ),
        migrations.AlterField(
            model_name='services',
            name='level',
            field=models.CharField(choices=[(b'sin experiencia', b'1'), (b'con bachillerato', b'2'), (b'carrera recien comenzada', b'3'), (b'carrera casi terminada', b'4'), (b'profesionista', b'5')], max_length=255),
        ),
    ]
